//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANA.Shop.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryProduct()
        {
            this.OrderCategoryProduct = new HashSet<OrderCategoryProduct>();
        }
    
        public int Id { get; set; }
        public int IdCategory { get; set; }
        public int IdProduct { get; set; }
        public bool Status { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCategoryProduct> OrderCategoryProduct { get; set; }
    }
}
