//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANA.Shop.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCategoryProduct
    {
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public int IdCategoryProduct { get; set; }
        public int Amount { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
